### ISSUE TITLE
Extension resources are not processed by sitemapgenerator

### ISSUE THREAD

**Issue by eddiewebb** [FriendsOfFlarum/sitemap#14]
I am including a link to code that exhibits simple test case. 

Please notice:
- The custom resource class constructor will be called. Any errors in this file will halt operation.
- The RegisterResource::extend method properly resolves the built-in and custom resources BUT
- When the SitemapGenerator::getUrlSet method loads the resources only built-in exist.

Since this seems to be from the Illuminate framework which I gleened is for container/dependency injection I'm lost unfamiliar beyond this point. 

"fof/sitemap": "^0.5.1"

resource: https://github.com/eddiewebb/flarum-calendar/blob/master/src/Integrations/EventResource.php
extend.php: https://github.com/eddiewebb/flarum-calendar/blob/master/extend.php#L51

(PR coming to show logging I added to this Plugin to debug the diff)

https://github.com/eddiewebb/sitemap/tree/eddiewebb-debug-14

Resulting logs:

```
[2020-07-21 21:45:10] production.DEBUG: [Webbinaro\AdvCalendar] Resource Initialized  
[2020-07-21 21:45:10] production.DEBUG: [RegisterResource::extend] added Webbinaro\AdvCalendar\Integrations\EventResource  
[2020-07-21 21:45:10] production.DEBUG: [RegisterResource::extend] resolved 4 resources.  
[2020-07-21 21:45:10] production.DEBUG: [SitemapGenerator::getUrlSet] resolved 3 resources.  
```

**Comment by eddiewebb** [comment]
This has to be a big in illuminate right? doesnt `make` just call the function in `resolving`?

**Comment by clarkwinkelmann** [comment]
I'm copying what I wrote in the PR here for future reference. It seems the extender we provide modifies an array which is incorrectly passed as value instead of the expected reference.

I wonder if nobody tried to use the extender ever? The issue would have been present since the introduction of the extender in January.
