### ISSUE TITLE
Error Installing sitemap

### ISSUE THREAD

**Issue by Madchatthew** [FriendsOfFlarum/sitemap#16]
When I try to install this extension I get the following error.

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - fof/console 0.5.3 requires dragonmantank/cron-expression ^1.2.1 -> satisfiable by dragonmantank/cron-expression[v1.2.1] but these conflict with your requirements or minimum-stability.
    - fof/sitemap 0.5.3 requires fof/console ^0.5.3 -> satisfiable by fof/console[0.5.3].
    - Installation request for fof/sitemap ^0.5.3 -> satisfiable by fof/sitemap[0.5.3].

Installation failed, reverting ./composer.json to its original content.
`

Here is my flarum info

`Flarum core 0.1.0-beta.13
PHP version: 7.4.9
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache
+-------------------------------+----------------+--------+
| Flarum Extensions             |                |        |
+-------------------------------+----------------+--------+
| ID                            | Version        | Commit |
+-------------------------------+----------------+--------+
| flarum-tags                   | v0.1.0-beta.13 |        |
| flarum-approval               | v0.1.0-beta.13 |        |
| noriods-auto-more             | 0.3.0          |        |
| flarum-bbcode                 | v0.1.0-beta.12 |        |
| clarkwinkelmann-circle-groups | 0.2.1          |        |
| flarum-emoji                  | v0.1.0-beta.13 |        |
| clarkwinkelmann-emojionearea  | 0.2.2          |        |
| flarum-auth-facebook          | v0.1.0-beta.13 |        |
| squeevee-fancybox             | 0.2-beta       |        |
| flarum-flags                  | v0.1.0-beta.13 |        |
| fof-custom-footer             | 0.1.3          |        |
| fof-follow-tags               | 0.3.6          |        |
| fof-formatting                | 0.1.5          |        |
| fof-ignore-users              | 0.1.6          |        |
| fof-links                     | 0.2.1          |        |
| fof-merge-discussions         | 0.3.3          |        |
| fof-profile-image-crop        | 0.1.2          |        |
| fof-reactions                 | 0.2.5          |        |
| fof-share-social              | 0.1.2          |        |
| fof-socialprofile             | 0.1.2          |        |
| fof-spamblock                 | 0.2.2          |        |
| fof-split                     | 0.4.4          |        |
| fof-terms                     | 0.4.3          |        |
| fof-upload                    | 0.9.2          |        |
| fof-user-bio                  | 0.1.3          |        |
| fof-user-directory            | 0.3.4          |        |
| fof-recaptcha                 | 0.1.2          |        |
| flarum-likes                  | v0.1.0-beta.13 |        |
| flarum-lock                   | v0.1.0-beta.13 |        |
| flarum-markdown               | v0.1.0-beta.13 |        |
| flarum-mentions               | v0.1.0-beta.13 |        |
| antoinefr-online              | 0.4.0          |        |
| v17development-seo            | 1.2.1          |        |
| flarum-statistics             | v0.1.0-beta.13 |        |
| flarum-sticky                 | v0.1.0-beta.13 |        |
| flarum-subscriptions          | v0.1.0-beta.13 |        |
| jordanjay29-summaries         | 0.3.1          |        |
| flarum-suspend                | v0.1.0-beta.13 |        |
| flarum-lang-english           | v0.1.0-beta.13 |        |
+-------------------------------+----------------+--------+
Base URL: https://whatsonyourscrubs.com
Installation path: /var/www/whatsonyourscrubs.com/html
Debug mode: off
`
If you need any other info, let me know. Thank you for your time.

**Comment by clarkwinkelmann** [comment]
Can you confirm you are running the commands in the Flarum directory that contains `composer.json` and `config.php`?

Does your `composer.json` file contains a line that says `"minimum-stability": "beta",` near the bottom?

Can you share the output of `composer why-not fof/sitemap`?

**Comment by Madchatthew** [comment]
> Can you confirm you are running the commands in the Flarum directory that contains `composer.json` and `config.php`?
> Yes, I am outside of the public folder and composer.json and config.php are visible.

> Does your `composer.json` file contains a line that says `"minimum-stability": "beta",` near the bottom?
>  There is a line that says "minimum-stability": "beta";

> Can you share the output of `composer why-not fof/sitemap`?
This is what I get when I put in the above.

  [InvalidArgumentException]
  Could not find package "fof/sitemap" in your project

**Comment by clarkwinkelmann** [comment]
I'm sorry we aren't more reactive on GitHub. I don't know what the issue is and am not sure what to suggest. If you are still experiencing the issue I suggest you ask on Discuss in the extension thread, maybe someone from outside the FoF team will be able to help.

**Comment by Madchatthew** [comment]
Sounds good. Thank you
