### ISSUE TITLE
Remove deleted & soft deleted articles

### ISSUE THREAD

**Issue by Gasjki** [FriendsOfFlarum/sitemap#21]
Hey! I created some articles, then I soft-deleted them (for a while, because I wanted to hide them for now). However, these articles are visible inside the `sitemap.xml`, even if I don't want them to be there.

Is this a bug or a known feature?

**Comment by clarkwinkelmann** [comment]
What mode (runtime/cache/multiple) are you using? If not runtime, have you correctly updated the sitemap?

The sitemap is supposed to generate with everything a guest can see.

**Comment by Gasjki** [comment]
I'm using this command: `php flarum fof:sitemap:cache --write-xml-file` for which I added a cron which runs 2 times / day.
In dashboard is marked as **Cache** and to run 2 times  / day. 

P.S.: I added that cron manually to crontab file. Should I remove it from there?

**Comment by luceos** [comment]
Please post the output of `php flarum info` or at least the version of this extension that you use. According to the code Discussions should only be inside the sitemap if they are visible to guests or are you talking about pages?

**Comment by Gasjki** [comment]
I'm using the latest version because I just did the installation a few days ago.  I agree with you, all discussions visible to visitors / members are inside that sitemap, but the problem is that I soft-deleted a few and they are still included in the sitemap.xml. I was thinking that they are not included anymore if they are soft-deleted. However, I can confirm that if you access discussion url of a soft-deleted post, you can view the post if you are mod / admin, but the discussion is not available for members / visitors.

**Comment by clarkwinkelmann** [comment]
I cannot replicate.

I did the following:

- Installed sitemap. Enabled disk mode
- Manually ran `php flarum fof:sitemap:cache --write-xml-file` in a terminal
- Check ID of last discussion at the end of the XML
- Went to Flarum, soft-deleted the discussion
- Manually ran `php flarum fof:sitemap:cache --write-xml-file` again
- Checked the new XML file. Discussion is gone

Obviously if we sitemap is only refreshed twice a day, there will be a moment where it will still show discussions that were deleted in the last 12 hours, but all should be removed once the CRON job runs again.

**Comment by Ralkage** [comment]
Since @clarkwinkelmann could not reproduce this issue and given that this issue has been inactive for quite some time, we will proceed with closing this issue.
