### ISSUE TITLE
FoF Sitemap: Multi mode will delete public/sitemap.xml file

### ISSUE THREAD

**Issue by Vicshs** [FriendsOfFlarum/sitemap#28]
## Bug Report

**Current Behavior**

Multi mode will delete public/sitemap.xml file.(多文件模式时会删除 `public/sitemap.xml` 文件)

**Expected Behavior**

You can remove calls to function names in `vendor/fof/sitemap/src/Commands/BuildSitemapCommand.php`, about line 160.（注释掉 vendor/fof/sitemap/src/Commands/BuildSitemapCommand.php 中的$this->forgetDisk() 函数调用，大概在160行）

**Screenshots**

![image](https://user-images.githubusercontent.com/26058795/122025994-6a12c600-cdfc-11eb-8c52-55b9e4a2add9.png)

**Environment**
- Flarum version: Flarum core 1.0.2
- Extension version: 1.0.0
- Website URL: https://www.zoulang.net/
- Webserver: nginx
- Hosting environment: vps
- PHP version: 7.3.28
- Browser: chrome 91

**Possible solution(s)**

注释掉 vendor/fof/sitemap/src/Commands/BuildSitemapCommand.php 中的$this->forgetDisk() 函数调用

**Comment by clarkwinkelmann** [comment]
I'm not familiar enough with that mode of operation. I suppose `sitemap.xml` is supposed to exist to link to the other multi-files?

Maybe @imorland will know better since he's the one who refactored that command last.

**Comment by pierres** [comment]
@Vicshs is completely right here. I successfully tested his change and created a PR. Would be great if this could end up in a new release as this issue pretty much renders the multi sitemap mode useless.
