### ISSUE TITLE
Deleted discussions and index problem

### ISSUE THREAD

**Issue by Turkmen48** [FriendsOfFlarum/sitemap#7]
Hi, I have a problem about sitemap extension. When I deleted a discussion, sitemap extension continues to indexing. But I have a solution for this problem.
1-) go to phpmyadmin
2-)find your db name
3-)find discussions table
4-)find deleted discussions
5-)click to delete button
6-)go to admin panel
7-)delete cache

this problem very important for seo. So as soon as possible please update extension.

**Comment by clarkwinkelmann** [comment]
Sorry we never replied, we must have missed your issue.

It's odd. Hidden "deleted" discussions should not be rendered in the sitemap. I just tested again on my PC and hidden discussions are properly ignored from the sitemap for me.

Are you using the command to cache or write the sitemap to disk or are you using the default where the sitemap is generated dynamically ?

**Comment by Turkmen48** [comment]
No ı dont using any command. Just ı checked my sitemap.xml and ı saw hidden
discussions rendered in sitemap. But now ı checked again and I saw hidden
discussion rendered again. Yeah ı know its odd. But not a big problem for
now.

9 Mart 2020 Pazartesi tarihinde Clark Winkelmann <notifications@github.com>
yazdı:

**Comment by clarkwinkelmann** [comment]
To help us replicate, could you share the output of the `php flarum info` command in your Flarum directory ? Any maybe try disabling all other third-party extensions to see if the problem persists or go away ?

The only possible reason I can guess with the information so far would be an incompatibility with another extension.

**Comment by Turkmen48** [comment]
Sorry ı cant do this. Because ı dont know how ı will send php flarum info.

10 Mart 2020 Salı tarihinde Clark Winkelmann <notifications@github.com>
yazdı:

**Comment by clarkwinkelmann** [comment]
To run the info command you can access your server via SSH, navigate to the Flarum folder with `cd` and run `php flarum info` in there. It's the same place where you have likely run `composer require [...]` to install extensions.

Then you can copy the output of that command in here. It will list all your extensions and their version.

**Comment by clarkwinkelmann** [comment]
I'm going to close this for now. Feel free to reply with additional details if the problem continues.
